/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package unittestdemo;

public class App {

    GreetingGenerator greetingGenerator;

    public App(GreetingGenerator greetingGenerator) {
        this.greetingGenerator = greetingGenerator;
    }

    public String getGreeting() {
        return greetingGenerator.getGreeting();
    }

    public static void main(String[] args) {
        System.out.println(new App(new GreetingGenerator()).getGreeting());
    }
}
