/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package unittestdemo;

public class App {

    public App(GreetingGenerator greetingGenerator) {

    }

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
